language: ruby
services:
- docker
before_install:
- docker build .
- docker ps -a
notifications:
  slack:
    secure: Ga56N2ROsTYSziK2dqBx9pTA9Wah65NuD1Qd6SiDVsJTYIHzNcNwEXi+vAG5i1AKOjyHJ5h8LNb2pQpPWmtczheN0h1etYecSu892K3eEtQE99qr+4CvhFeVSj7kL5cTX2U4s6jpxZyv5dw/X45/wAbOGfnWhR1iUVJguPfV3aXA3+Mgn2lTKZqBnYlYjzIGanyJWFIDDrmbFffbjXVl1B3JtLoQud1ICd0dPFihruh95J3CxgntGgXzEAmnZXsCXxpyL6Y17vI1S7ZCczl8I++ZBvQ0tNaNuzhTWqgA8h0C/TpsSTFiWpHGqTfEuYtvFWwTnLGDWM3sUnOLwzXcogborB5I/78Vh7bPzhocrzzDE/7Mf6/C27jC2XNQDLFmQk6pm2C1Q2K9Cn9d5neCZ1WzRruwp2wyb56YBzlCXNISMXXmSP++4UmJFhVx8HjkcHTL62tNuCws9XzeVNCOVu+pXin1Ke76hcxTEoin+aPtHJ73tK2rjPb9iFA/uK5MNG6HMubJZs83Yq4JsNhw0vMSTPO7AkchmL7eCis83d+8KGqiwiNqCeHno511pgpEdDl4vrp/R0KheJc5x55QN4VbJ4rGFQdHxmUeqRd9ZOmkBh0IW0yXl9uto5JlEnk9+VWvCTel2ZXfSZS4dncpt6IVxMeVGq/7Vb+5OeGoSs4=
